# Generated by Django 5.0.6 on 2024-05-19 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haccp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haccpbackburnerfreezer',
            name='corrective_action',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(-18.0)]),
        ),
        migrations.AlterField(
            model_name='haccpbackburnerfridge',
            name='corrective_action',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
